# Exercise 3: Numpy

Perform the follwing tasks:


In [0]:
#3.1: import the numpy library
import numpy as np


In [5]:
#3.2: create a random 10x10 array named A
A = np.random.rand(10,10)
A


array([[0.00358504, 0.51153778, 0.98220603, 0.08720383, 0.31596988,
        0.78566027, 0.97286636, 0.20413489, 0.95666732, 0.21807367],
       [0.39377438, 0.06580004, 0.56778035, 0.64315436, 0.54711289,
        0.1106748 , 0.24313021, 0.63176762, 0.35564667, 0.12838934],
       [0.23676412, 0.3137613 , 0.80678152, 0.79472314, 0.88216975,
        0.03048697, 0.84328969, 0.46593294, 0.28958604, 0.05564328],
       [0.20259378, 0.97686182, 0.63752831, 0.2021256 , 0.1515324 ,
        0.48522416, 0.41116814, 0.36599951, 0.72439994, 0.70154475],
       [0.53087944, 0.47488449, 0.16190234, 0.48121506, 0.19581615,
        0.3269171 , 0.86442285, 0.83234407, 0.6441323 , 0.42563661],
       [0.24301108, 0.4819224 , 0.76362666, 0.87092236, 0.44401547,
        0.74165732, 0.89834297, 0.05144054, 0.79043073, 0.36256678],
       [0.80581956, 0.81431282, 0.68612416, 0.4635035 , 0.22439645,
        0.42814477, 0.71477214, 0.74204919, 0.11107846, 0.99088972],
       [0.66406262, 0.10998245, 0.4589864

In [7]:
#3.3: return only the odd rows of A
A[::2]

array([[0.00358504, 0.51153778, 0.98220603, 0.08720383, 0.31596988,
        0.78566027, 0.97286636, 0.20413489, 0.95666732, 0.21807367],
       [0.23676412, 0.3137613 , 0.80678152, 0.79472314, 0.88216975,
        0.03048697, 0.84328969, 0.46593294, 0.28958604, 0.05564328],
       [0.53087944, 0.47488449, 0.16190234, 0.48121506, 0.19581615,
        0.3269171 , 0.86442285, 0.83234407, 0.6441323 , 0.42563661],
       [0.80581956, 0.81431282, 0.68612416, 0.4635035 , 0.22439645,
        0.42814477, 0.71477214, 0.74204919, 0.11107846, 0.99088972],
       [0.67523796, 0.33373428, 0.28504606, 0.74778852, 0.43380556,
        0.57624152, 0.80207763, 0.21832448, 0.71960082, 0.03675385]])

In [8]:
#3.4: perform a matrix multiplication of A with it's transposed
A.dot(A.T)

array([[3.90202447, 1.6423906 , 2.53046279, 2.89406244, 2.48444647,
        3.51607939, 2.71026208, 2.49863791, 2.62943762, 2.78464932],
       [1.6423906 , 1.80820239, 2.17862693, 1.45153055, 1.80477575,
        2.02469769, 2.03802977, 1.88504752, 1.82533624, 2.02510989],
       [2.53046279, 2.17862693, 3.23132487, 1.94399609, 2.29744687,
        2.96187815, 2.61501512, 2.59528868, 2.47763758, 2.86891624],
       [2.89406244, 1.45153055, 1.94399609, 3.02094011, 2.38550638,
        2.82516825, 3.07268404, 2.15105065, 2.09778401, 2.26134424],
       [2.48444647, 1.80477575, 2.29744687, 2.38550638, 2.94644379,
        2.71283491, 3.06134962, 2.35428909, 2.55049849, 2.7478862 ],
       [3.51607939, 2.02469769, 2.96187815, 2.82516825, 2.71283491,
        3.94604197, 3.0603946 , 3.026433  , 3.12774082, 3.21396074],
       [2.71026208, 2.03802977, 2.61501512, 3.07268404, 3.06134962,
        3.0603946 , 4.28745118, 2.76030719, 2.55378428, 2.64594559],
       [2.49863791, 1.88504752, 2.5952886

In [12]:
#3.5: compute the matrix inverse of A
np.linalg.inv(A)

array([[ 0.3807842 ,  0.19605568, -0.59024131, -0.10356551, -1.42272101,
        -1.73605002,  0.89761898,  0.3191379 ,  1.73539968,  0.65879405],
       [-0.55584106, -0.90395435,  0.94578978,  1.40009279, -0.35000489,
        -0.56964695, -0.12560679, -0.51136203,  0.94516293, -0.09867356],
       [ 0.89041246,  0.71012505, -0.43608047, -0.27402178, -1.68521887,
        -0.75325616,  0.84914963, -0.02131109,  0.10725734,  0.91327921],
       [-0.93299123,  0.29382247, -0.13681154, -0.05604132, -0.00441997,
         1.32289418, -0.07861129, -0.30823659, -0.2794629 ,  0.29849723],
       [-0.37965606, -0.1041132 ,  1.25702795,  0.5220611 ,  0.86978823,
         0.23713496, -0.87522594,  0.31799648, -0.09321917, -1.39889363],
       [ 0.03925565,  0.40650388, -0.20139867, -0.46009986,  0.93874575,
         1.5923493 , -0.14722953, -0.6156938 , -0.06460354, -1.44282349],
       [ 0.42918802, -1.20416642,  0.48305004, -0.82579067,  0.50379634,
        -0.07195024,  0.31765886,  0.13482951

In [22]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )
indices = np.where(A > 0.5)

A[indices] /2


array([0.25576889, 0.49110301, 0.39283014, 0.48643318, 0.47833366,
       0.28389017, 0.32157718, 0.27355644, 0.31588381, 0.40339076,
       0.39736157, 0.44108487, 0.42164485, 0.48843091, 0.31876416,
       0.36219997, 0.35077237, 0.26543972, 0.43221142, 0.41617203,
       0.32206615, 0.38181333, 0.43546118, 0.37082866, 0.44917148,
       0.39521536, 0.40290978, 0.40715641, 0.34306208, 0.35738607,
       0.37102459, 0.49544486, 0.33203131, 0.28792936, 0.40573547,
       0.36156372, 0.33727608, 0.33496144, 0.33761898, 0.37389426,
       0.28812076, 0.40103881, 0.35980041, 0.27011908, 0.47797296,
       0.4912865 , 0.25263212, 0.40741841])